config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"
  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, only: [:index, :show] do
        resources :reports, only: [:index, :show, :destroy]
      end
      resources :my_posts, except:  [:edit, :new] do
        resources :reports, only: [:index, :show]
        resources :stations, only: [:index] do
          resources :reports, only: [:index]
        end
      end
      resources :users, only: [:show]
    end
  end

  resources :posts

  resources :mi_reports, only: [:create]

  resources :reports, only: [:create] do
    get :autocomplete_station, :on => :collection
    get :autocomplete_config, :on => :collection
    collection do
      get :search
      post :import
    end
  end

  resources :my_posts, only: [:index, :show, :destroy] do
    resources :reports, only: [:show] do
      get :autocomplete_station_name, :on => :collection
      get :autocomplete_report_config, :on => :collection
      collection do
        get :search
      end
      resources :configs, only: [:index]
    end
    resources :stations, only: [:show]
    resources :yield_files, only: [:index, :show, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end
  end

  match "/update_builds_selector" => "products#update_builds_selector"
  match "/update_builds_menu" => "products#update_builds_menu"
  match "/delete_account" => "accounts#checkpass"

  match "/search_report" => "reports#search"

  root :to => 'main#index'

  get '*anything' => 'errors#routing_error'

end

app/models/user.rb
#require 'Houston'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :provider, :uid

  attr_accessor :facebook_user

  has_many :devices, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :products, :dependent => :destroy
  has_many :access_grants, :dependent => :destroy, :class_name => "Doorkeeper::AccessGrant", :foreign_key => "resource_owner_id"
  has_many :access_tokens, :dependent => :destroy, :class_name => "Doorkeeper::AccessToken", :foreign_key => "resource_owner_id"

  # validates_presence_of   :email, :if => :email_required?
  # validates_uniqueness_of :email, :allow_blank => true, :if => :email_changed?
  # validates_format_of     :email, :with  => email_regexp, :allow_blank => true, :if => :email_changed?

  # validates_presence_of     :password, :if => :password_required?
  # validates_confirmation_of :password, :if => :password_required?
  # validates_length_of       :password, :within => password_length, :allow_blank => true

  def self.send_notify_ios(text, data = nil)
    certificate = File.read(ENV['APPLE_CERTIFICATE'])
    passphrase = ENV['APN_CERTIFICATE_PASSPHRASE']
    connection = Houston::Connection.new(Houston::APPLE_DEVELOPMENT_GATEWAY_URI, certificate, passphrase)
    connection.open

    #apn = Houston::Client.development
    #apn.certificate = File.read(ENV['APPLE_CERTIFICATE']) # certificate from prerequisites
    Device.where(platform: 'ios').each do |device|
      notification = Houston::Notification.new(device: device.uuid)
      notification.alert = text
      notification.badge = 1
      notification.content_available = true
      notification.mutable_content = true
      #notification.sound = 'sound.aiff'
      #notification.category = 'INVITE_CATEGORY'
      #notification.custom_data = { foo: 'bar', alice: 'bob' }
      notification.custom_data = data unless data.nil?
      connection.write(notification.message)
      connection.close
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(
        # name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    if user.valid?
      user.facebook_token = auth.credentials.token
      user.facebook_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def facebook
    if !@facebook && facebook_token && facebook_expires_at > Time.now
      @facebook = Koala::Facebook::API.new(facebook_token)
    end
    @facebook
  end
end

app/controllers/api/v1/my_posts_controller.rb
class Api::V1::MyPostsController < Api::ApiController
  doorkeeper_for :all

  def index
    page = (params[:page] || 1).to_i
    expires_in 5.seconds
    if page > 1 || stale?(last_modified: current_user.posts.maximum(:updated_at))
      @posts = current_user.posts.alive.order("updated_at DESC").page(page)
    end
  end

  def show
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      render_error(
        :resource_not_found,
        "Not Found",
        "Requested post does not exist or you don't have permission to see it."
      )
      return
    end
    expires_in 5.seconds
    fresh_when @post
  end

  def create
    @post = current_user.posts.create(params[:post])
    unless @post.valid?
      render_error(:invalid_parameter, "Parameter Error", @post.errors.messages)
      return
    end
    render :action => :show
  end

  def update
    @post = current_user.posts.find_by_id(params[:id])
    @post.update_attributes(params[:post])
    unless @post.valid?
      render_error(:invalid_parameter, "Parameter Error", @post.errors.messages)
      return
    end
    render :action => :show
  end

  def destroy
    @post = current_user.posts.find_by_id(params[:id])
    @post.destroy
    #@post.update_attribute(:deleted_at, Time.now)
    render :action => :show
  end
end

app/controllers/my_posts_controller.rb
class MyPostsController < InheritedResources::Base
  defaults :resource_class => Post, :collection_name => 'posts', :instance_name => 'post'
  before_filter :authenticate_user!

  def index
    @posts = Post.find(:all, order: 'title')
    @files_count = YieldFile.find(:all).count
  end

  def show
    page = (params[:page] || 1).to_i
    @posts = Post.find(:all, order: 'title')
    @post = Post.find(params[:id])
    reports_by_all = @post.reports
    reports_count = @post.reports.count

    if reports_count > 0
      if params[:date] == 'today'
        if reports_count == 0
          redirect_to my_post_path(@post), alert: "No data found :("
          return
        else
          @reports_for_cart = get_today_yield(@post, reports_by_all)
        end
      elsif params[:date] == 'yesterday'
        if reports_count == 0
          redirect_to my_post_path(@post), alert: "No data found :("
          return
        else
          @reports_for_cart = get_yesterday_yield(@post, reports_by_all)
        end
      elsif params[:to_date].present? && params[:to_date] != ""
        if reports_count == 0
          redirect_to my_post_path(@post), alert: "No data found :("
          return
        else
          @reports_for_cart = get_custom_date_yield(@post, reports_by_all, params[:to_date])
        end
      else # Today
        @reports_for_cart = get_today_yield(@post, reports_by_all)
      end
      reports_tmp = @reports_for_cart
      @reports_for_cart = reports_tmp.order("published_at ASC")
      @reports = reports_tmp.order("station_id ASC").page(page)
    else
      respond_to do |format|
        format.js { head :ok }
        format.html { redirect_to my_posts_path, alert: "No data found :(" }
        format.json { head :no_content }
      end
    end

  end

  # def new
  #   @product = Product.find(params[:product_id])
  #   @post = Post.new
  # end

  # def create
  #   create! { product_my_posts_path }
  #   @post.user = current_user
  #   @post.product = Product.find(params[:product_id])
  #   @post.save
  # end

  # def edit
  #   @product = Product.find(params[:product_id])
  #   @post = Post.find(params[:id])
  # end

  # def update
  #   @product = Product.find(params[:product_id])
  #   @post = Post.find(params[:id])
  #   update! { product_my_post_path(@product, @post) }
  # end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.js { head :ok }
      format.html { redirect_to my_posts_path, notice: "#{@post.title} was removed :)" }
      format.json { head :no_content }
    end
  end

  protected

  def begin_of_association_chain
    current_user
  end

  def collection
    @posts ||= end_of_association_chain.order("updated_at DESC")
    # @posts ||= end_of_association_chain.page((params[:page] || 1).to_i)
  end

end

app/helpers/api/v1/my_posts_helper.rb
module Api::V1::MyPostsHelper
end

app/helpers/my_posts_helper.rb
module MyPostsHelper
end

app/views/my_posts/_form.html.haml
.row
  .container
    = form_for(@post, :url => (@post.id ? product_my_post_path(@product, @post) : product_my_posts_path(@product)), :html => { :class => "well", :role => "form" }) do |f|
      - if @post.errors.any?
        #error_explanation
          %h2
            = pluralize(@post.errors.count, "error")
            prohibited this post from being saved:
          %ul
            - @post.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :title
        = f.text_field :title, :style => "width: 99%;", class: "form-control", placeholder: "Build & Stage"
      .form-group
        = f.label :content
        = f.text_area :content, :style => "width: 99%;", class: "form-control", placeholder: "Description for this build & stage"
      .checkbox
        %label.checkbox{ :for => "post_publish" }
          - @post.publish = @post.published if @post.publish.nil?
          - @post.publish = true unless @post.created_at
          = f.check_box :publish
          Publish
      
      %button{ :type => "submit", :class => "btn btn-primary" } Save it
      = link_to 'Cancel', product_my_posts_path, class: "btn btn-default"

app/views/my_posts/_worst_yield_cart.html.haml
%div
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "best-shares-p", "data-toggle" => "tab", :href => "#best-shares-p", :role => "tab"} 股數百分比
    %li{:role => "presentation"}
      %a{"aria-controls" => "best-closing-p", "data-toggle" => "tab", :href => "#best-closing-p", :role => "tab"} 成交百分比

  .tab-content
    #best-shares-p.tab-pane.fade.in.active{:role => "tabpanel"}
      - if @reports_for_cart.count > 0
        .small{style: "margin-top: 15px; text-align: center;"}
          %strong
            股數百分比Top5的分類指數圖表
        .chart-tags
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #cb4b4b;"}
            %span.badge-category 少量佔比 (0 ~ 9.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #f8aa33;"}
            %span.badge-category 一般佔比 (10.00 ~ 49.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #1fbba6;"}
            %span.badge-category 多量佔比 (50.00 ~ 100 %)

        = content_tag :div, "", id: "best-shares-p-yield-data", data: {reports: best_percentage_chart_data(@reports_for_cart)}
      - else
        .well{:style => "margin-top: 10px;"}
          .blankslate.text-center
            %h3 沒有資料
            %p 抱歉，沒有資料可以呈現圖表

    #best-closing-p.tab-pane.fade{:role => "tabpanel"}
      - if @reports_for_cart.count > 0
        .small{style: "margin-top: 15px; text-align: center;"}
          %strong
            成交百分比Top5的分類指數圖表
        .chart-tags
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #ff7070;"}
            %span.badge-category 少量佔比 (0 ~ 9.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #ffc652;"}
            %span.badge-category 一般佔比 (10.00 ~ 49.99 %)
          .badge-wrapper.bullet
            %span.badge-category-bg{:style => "background-color: #4da74d;"}
            %span.badge-category 多量佔比 (50.00 ~ 100 %)

        = content_tag :div, "", id: "best-closing-p-yield-data", data: {reports: best_percentage_chart_data(@reports_for_cart)}
      - else
        .well{:style => "margin-top: 10px;"}
          .blankslate.text-center
            %h3 沒有資料
            %p 抱歉，沒有資料可以呈現圖表
            
:javascript
  jQuery(function() {
    $('ul.nav a').on('shown.bs.tab', function (e) {
      best_shares_percentage_graph.redraw();
      best_closing_percentage_graph.redraw();
      $('svg').css({ width: '100%' });
    });

    var best_shares_percentage_graph = Morris.Bar({
      element: 'best-shares-p-yield-data',
      smooth: true,
      continuousLine: true,
      behaveLikeLine: true,
      barColors: function(row, series, type) {
        if (type === 'bar') {
          if (row.y >= 50.00 && row.y <= 100) {
            return '#1fbba6';
          } else if (row.y >= 10.00 && row.y <= 49.99) {
            return '#f8aa33';
          } else if (row.y >= 0 && row.y <= 9.99) {
            return '#cb4b4b';
          }
        } else {
          return '#000';
        }
      },
      lineWidth: 4,
      fillOpacity: 0.8,
      resize: true,
      hideHover: 'auto',
      continuousLine: true,
      data: $('#best-shares-p-yield-data').data('reports'),
      goals: [0, 50, 100],
      goalLineColors: ['#e74c3c', '#e67e22', '#2ecc71'],
      xkey: 'published_at',
      ykeys: ['best1_shares_percentage', 'best2_shares_percentage', 'best3_shares_percentage', 'best4_shares_percentage', 'best5_shares_percentage'],
      labels: ['best1_shares_percentage_index', 'best2_shares_percentage_index', 'best3_shares_percentage_index', 'best4_shares_percentage_index', 'best5_shares_percentage_index'],
      "hoverCallback":  function(index, options, content){
        var row = options.data[index]
        datetime = '<p><b>' + row.published_at + '</b></p>'
        var top1_index = row.best1_shares_percentage + options.postUnits;
        var top2_index = row.best2_shares_percentage + options.postUnits;
        var top3_index = row.best3_shares_percentage + options.postUnits;
        var top4_index = row.best4_shares_percentage + options.postUnits;
        var top5_index = row.best5_shares_percentage + options.postUnits;

        p_index1 = '<div style="color: #555;"><strong>Top1: </strong>' + row.best1_shares_percentage_index + ' (' + top1_index + ')</div>'
        p_index2 = '<div style="color: #555;"><strong>Top2: </strong>' + row.best2_shares_percentage_index + ' ('  + top2_index + ')</div>'
        p_index3 = '<div style="color: #555;"><strong>Top3: </strong>' + row.best3_shares_percentage_index + ' ('  + top3_index + ')</div>'
        p_index4 = '<div style="color: #555;"><strong>Top4: </strong>' + row.best4_shares_percentage_index + ' ('  + top4_index + ')</div>'
        p_index5 = '<div style="color: #555;"><strong>Top5: </strong>' + row.best5_shares_percentage_index + ' ('  + top5_index + ')</div>'
        
        return [datetime, p_index1, p_index2, p_index3, p_index4, p_index5]
      },
      trendLine: true,
      postUnits: '%',
      ymin: 'auto',
      ymax: 'auto',
      parseTime: false,
      barOpacity: 0.8,
      behaveLikeLine: true
    });

    var best_closing_percentage_graph =  Morris.Bar({
      element: 'best-closing-p-yield-data',
      smooth: true,
      continuousLine: true,
      behaveLikeLine: true,
      barColors: function(row, series, type) {
        if (type === 'bar') {
          if (row.y >= 50.00 && row.y <= 100) {
            return '#4da74d';
          } else if (row.y >= 10.00 && row.y <= 49.99) {
            return '#ffc652';
          } else if (row.y >= 0 && row.y <= 9.99) {
            return '#ff7070';
          }
        } else {
          return '#000';
        }
      },
      lineWidth: 4,
      fillOpacity: 0.8,
      resize: true,
      hideHover: 'auto',
      continuousLine: true,
      data: $('#best-closing-p-yield-data').data('reports'),
      goals: [0, 50, 100],
      goalLineColors: ['#e74c3c', '#e67e22', '#2ecc71'],
      xkey: 'published_at',
      ykeys: ['best1_closing_percentage', 'best2_closing_percentage', 'best3_closing_percentage', 'best4_closing_percentage', 'best5_closing_percentage'],
      labels: ['best1_closing_percentage_index', 'best2_closing_percentage_index', 'best3_closing_percentage_index', 'best4_closing_percentage_index', 'best5_closing_percentage_index'],
      "hoverCallback":  function(index, options, content){
        var row = options.data[index]
        datetime = '<p><b>' + row.published_at + '</b></p>'
        var top1_index = row.best1_closing_percentage + options.postUnits;
        var top2_index = row.best2_closing_percentage + options.postUnits;
        var top3_index = row.best3_closing_percentage + options.postUnits;
        var top4_index = row.best4_closing_percentage + options.postUnits;
        var top5_index = row.best5_closing_percentage + options.postUnits;

        c_index1 = '<div style="color: #555;"><strong>Top1: </strong>' + row.best1_closing_percentage_index + ' (' + top1_index + ')</div>'
        c_index2 = '<div style="color: #555;"><strong>Top2: </strong>' + row.best2_closing_percentage_index + ' ('  + top2_index + ')</div>'
        c_index3 = '<div style="color: #555;"><strong>Top3: </strong>' + row.best3_closing_percentage_index + ' ('  + top3_index + ')</div>'
        c_index4 = '<div style="color: #555;"><strong>Top4: </strong>' + row.best4_closing_percentage_index + ' ('  + top4_index + ')</div>'
        c_index5 = '<div style="color: #555;"><strong>Top5: </strong>' + row.best5_closing_percentage_index + ' ('  + top5_index + ')</div>'
        
        return [datetime, c_index1, c_index2, c_index3, c_index4, c_index5]
      },
      postUnits: '%',
      ymin: 'auto',
      ymax: 'auto',
      parseTime: false,
      barOpacity: 0.8,
      behaveLikeLine: true
    });
  });

app/views/my_posts/edit.html.haml
%header.page-header
  %h2 Edit YieldReport

= render 'form'

app/views/my_posts/index.html.haml
- navigation_add 'Modules', my_posts_path

%h2.page-header
  Modules
  %small
    功能模組
%p.lead 請從下面清單進入中一個模組

.row
  .build-lists
    .col-md-8.col-md-offset-2
      .panel.panel-custom.panel-default
        .panel-body
          .pull-right
            .table
              .btn-group
                %button.btn.btn-primary{"data-toggle" => "modal", href: "#importCSV"}
                  %span.glyphicon.glyphicon-cloud-upload{"aria-hidden" => "true"}
                  匯入CSV資料

          .table-container
            %table.table.table-hover.table-filter
              %tbody
                - if @posts.count > 0
                  - @posts.each do |post|
                    %tr{id: "build_row_#{post.id}"}
                      %td{style: "vertical-align: middle;"}
                        .ckbox
                          = check_box_tag "post_ids[]", post.id, false, id: "post_ids_#{post.id}"
                          %label{for: "post_ids_#{post.id}"}
                      %td{style: "vertical-align: middle;"}
                        %a.star{href: "javascript:;", "data-toggle" => "tooltip", title: "給你按爽的，目前無作用"}
                          %i.glyphicon.glyphicon-star
                      %td
                        .media
                          .media-body
                            %span.media-meta.pull-right
                              於
                              = post.created_at.to_date.to_formatted_s(:long)
                              建立
                            %h4.title
                              = link_to post.title, my_post_path(post)
                              %span#delete-build.pull-right.dont_show
                                = link_to '(刪除模組)', '#', class: "text-danger", id: "delete-a-build", "data-build-name" => "#{post.title}", "data-build-id" => "#{post.id}"
                              %span#manage-files.pull-right.dont_show
                                = link_to '(管理文件)', my_post_yield_files_path(post)
                            %p.summary
                              - if post.reports.count > 0
                                共
                                = @files_count
                                個文件
                                %br
                                包含
                                = post.reports.count.to_i
                                筆指數及
                                = post.mi_reports.count.to_i
                                筆證券資料
                              - else
                                沒有資料
                - else
                  %tr
                    %td
                      沒有以建立的模組 :(

= render :partial => "shared/csv_importer"

:javascript
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();

    $('.star').on('click', function () {
      $(this).toggleClass('star-checked');
    });

    $('.ckbox label').on('click', function () {
      $(this).parents('tr').toggleClass('selected');
      var checked = $(this).find("input:checkbox").is(":checked");
      if(checked){
        $(this).parents('tr').find('#delete-build').removeClass('dont_show');
        $(this).parents('tr').find('#manage-files').removeClass('dont_show');
      }
      else {
        $(this).parents('tr').find('#delete-build').toggleClass('dont_show');
        $(this).parents('tr').find('#manage-files').toggleClass('dont_show');
      }
    });
  });

  $("a#delete-a-build").click(function() {
    var buildName = $(this).attr("data-build-name");
    var buildId = $(this).attr("data-build-id");
    deleteBuild(buildName, buildId);
  });

  function deleteBuild(buildName, buildId) {
    swal({
      title: "Are you sure?", 
      text: "You want to delete " + buildName, 
      type: "warning",
      showCancelButton: true,
      closeOnConfirm: false,
      confirmButtonClass: "btn-warning",
      confirmButtonText: "Delete it!",
      closeOnConfirm: false,
      showLoaderOnConfirm: true
    }, function() {
      $.ajax({
        url: "/my_posts/" + buildId,
        type: "DELETE",
        dataType: 'script'
      })
      .done(function(data) {
        swal("成功刪除", buildName + " 模組，以及所有資料已成功清除！", "success");
        $("#build_row_" + buildId).fadeOut();

        $('button.confirm').click(function() {
          setTimeout(function(){
            $(location).attr('href', "/my_posts")
          }, 200);
        });
      })
      .error(function(data) {
        swal("發生未知錯誤！", "抱歉，我們無法連接到伺服器！", "error");
      });
    });
  }

app/views/my_posts/new.html.haml
- navigation_add 'Products', products_path
- navigation_add 'Add build & stage', new_product_my_post_path

%h2.page-header
  = @product.title
  %small Add build & stage
%p.lead Create new build & stage to organize and manage daily yield report

= render 'form'

app/views/my_posts/show.html.haml
- build_type = params[:build].nil? ? "" : " (" + params[:build].to_s.upcase + ")"

- navigation_add 'Modules', my_posts_path
- navigation_add @post.title + build_type, my_post_path(@post)

%h2.page-header
  = @post.title + build_type
  %small 各分類指數&證券資料查詢

.form-group
  .row
    .col-md-12
      #yield-report
        / .section_topic
        /   %h3.image_title
        /     %img{:alt => "Topic", :src => "/assets/topic_title.png"}
        /     %p= @post.title + build_type
        = render :partial => "shared/yield_report"

app/views/my_posts/show.js.erb
//$('#yield-items').html("<%= j(render :partial => 'shared/yield_items') %>");
$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
$('#paginator-top').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
$('#page-info').html("<%= j(render :partial => 'shared/page_info_scroll') %>");
//$('#date-selector').html("<%= j(render :partial => 'shared/date_selector') %>");
$('#date-range').html("<%= j(render :partial => 'shared/date_range') %>");
$('#worst-yield-cart').html("<%= j(render :partial => 'worst_yield_cart') %>");
$("#paginator .pagination").rPage();
$('.dropdown-toggle').dropdown();

// Append new report data
$("<%=j render(:partial => 'shared/items', :object => @reports) %>").appendTo($(".infinite-table"));
// Update pagination link
<% if @reports.last_page? %>
  $('.pagination').html("That's all, dude!");
<% else %>
  //$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
  $('#paginator').html('<%= escape_javascript(link_to_next_page(@reports, 'Load more report', params: params, :remote => true).to_s) %>');
<% end %>