config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"
  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, only: [:index, :show] do
        resources :reports, only: [:index, :show, :destroy]
      end
      resources :my_posts, except:  [:edit, :new] do
        resources :reports, only: [:index, :show]
        resources :stations, only: [:index] do
          resources :reports, only: [:index]
        end
      end
      resources :users, only: [:show]
    end
  end

  resources :posts

  resources :mi_reports, only: [:create]

  resources :reports, only: [:create] do
    get :autocomplete_station, :on => :collection
    get :autocomplete_config, :on => :collection
    collection do
      get :search
      post :import
    end
  end

  resources :my_posts, only: [:index, :show, :destroy] do
    resources :reports, only: [:show] do
      get :autocomplete_station_name, :on => :collection
      get :autocomplete_report_config, :on => :collection
      collection do
        get :search
      end
      resources :configs, only: [:index]
    end
    resources :stations, only: [:show]
    resources :yield_files, only: [:index, :show, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end
  end

  match "/update_builds_selector" => "products#update_builds_selector"
  match "/update_builds_menu" => "products#update_builds_menu"
  match "/delete_account" => "accounts#checkpass"

  match "/search_report" => "reports#search"

  root :to => 'main#index'

  get '*anything' => 'errors#routing_error'

end

app/views/shared/_builds_selector.html.haml
- if @builds.nil?
  = select_tag "my_post_id", nil, class: 'form-control', id: 'selected-build', prompt: '', disabled: true, style: "width: 100%"
- else
  = select_tag "my_post_id", options_for_select(@builds.collect{ |b| [b.title, b.id] }), class: 'form-control', id: 'selected-build', style: "width: 100%"

:javascript
  $('#selected-build').select2({
    placeholder: ""
  });

app/views/shared/_configs_selector.html.haml
- if @builds.nil? || (params[:product_id] == "" && @builds.count == 0)
  = text_field_tag :config, params[:config], id: 'search-config', class: 'form-control', placeholder: 'Config Name', :disabled => true
- else
  = autocomplete_field_tag :config, '', autocomplete_config_reports_path, id: 'search-config', class: 'form-control', placeholder: 'Config Name', :append_to => "#config-list-suggested", :disabled => true
  #config-list-suggested

app/views/shared/_csv_importer.html.haml
#importCSV.modal{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", "data-backdrop" => "true", "data-keyboard" => "false"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4.modal-title 匯入CSV文件

      .modal-body
        %ul.list-group
          %li.list-group-item.list-group-item-warning 此功能僅在開發階段使用，系統每天會自動抓取指數和證券資料，您無須手動操作！

        %ul.nav.nav-pills.mb-3{:role => "tablist"}
          %li.active{:role => "presentation"}
            %a{"aria-controls" => "bfiamu-import-tab", "data-toggle" => "pill", :href => "#bfiamu-import-tab", :role => "tab"}
              匯入指數資料
          %li{:role => "presentation"}
            %a{"aria-controls" => "mi-index-import-tab", "data-toggle" => "pill", :href => "#mi-index-import-tab", :role => "tab"}
              匯入證券資料

        .tab-content
          #bfiamu-import-tab.tab-pane.fade.in.active{:role => "tabpanel"}
            %h4 請從本地端目錄選取CSV文件
            %p.text-danger *欲匯入[指數資料]，請從台灣證券交易所網站，下載CSV格式文件到你的文件夾裡，然後選取檔名格式為"YYYYMMDD.csv"的文件（例如：20200226.csv），或是選取一個包含所有正確格式CSV文件的整個文件夾，來批次匯入多個文件 (後者僅支持Chrome)
            #import-yield-report
              = render :partial => "shared/import_form"

          #mi-index-import-tab.tab-pane.fade{:role => "tabpanel"}
            %h5 請從本地端目錄選取CSV文件
            %p.text-danger *欲匯入[證券資料]，請從台灣證券交易所網站，下載CSV格式文件到你的文件夾裡，然後選取檔名格式為"MI-INDEX-NN-YYYYMMDD.csv"的文件（例如：MI-INDEX-01-20200226.csv），或是選取一個包含所有正確格式CSV文件的整個文件夾，來批次匯入多個文件 (後者僅支持Chrome)
            %small
              檔名中的 NN 是分類指數編號（01~31，沒有19），編號對應的指數類型如下：
              %br
              01水泥工業、02食品工業、03塑膠工業、04紡織纖維、05電機機械、06電器電纜、07化學生技醫療、08玻璃陶瓷、09造紙工業、10鋼鐵工業、11橡膠工業、12汽車工業、13電子工業、14建材營造、15航運業、16觀光事業、17金融保險、18貿易百貨、20其他、21化學工業、22生技醫療業、23油電燃氣業、24半導體業、25電腦及週邊設備業、26光電業、27通信網路業、28電子零組件業、29電子通路業、30資訊服務業、31其他電子業
              %br
            #import-yield-report
              = render :partial => "shared/mi_import_form"

app/views/shared/_footer.html.haml
%footer
  .footer-content
    .row
      .col-md-6.footer-left
        %ul.list-inline
          %li
            %a{:href => "/"} 首頁
            |
          %li
            %a{:href => "#"} 關於我們
            |
          %li
            %a{:href => "#"} 服務內容
            |
          %li
            %a{:href => "#"} 聯繫我們

      .col-md-6.footer-right
        %p
          Powered by 
          %strong Linode
    %hr
    .row
      .col-lg-12.footer-below
        %p.copyright.text-muted.small
          Copyright &copy;
          =title
          2020. All Rights Reserved

app/views/shared/_import_form.html.haml
.form-group
  /= label_tag :file, "Choose CSV file to import", class: "control-label file_upload"
  = form_tag(reports_path, method: 'post', remote: true, multipart: true) do
    %p
      %input#js-csv-upload.file-loading{:accept => "text/csv", :multiple => "multiple", :name => "file[]", :type => "file", :webkitdirectory => ""}
      #kv-success-1.alert.alert-success.fade.in{:style => "margin-top:10px; display:none"}
      #kv-error-1{:style => "margin-top:10px; display:none"}
      /= file_field_tag :file, class: 'js-csv-upload', accept: 'text/csv'

:javascript
  jQuery(function() {
    var importedFiles = 0
    var notImportedFiles = 0
    $('#js-csv-upload').fileinput({
      uploadUrl: "/reports",
      uploadAsync: true,
      showPreview: false,
      showUpload: true,
      elErrorContainer: '#kv-error-1',
      browseOnZoneClick: true,
      browseClass: 'btn btn-info fileinput-browse-button',
      browseLabel: "選取文件",
      browseIcon: "<i class=\"glyphicon glyphicon-folder-open\"></i> ",
      removeClass: 'btn btn-danger',
      removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
      removeLabel: 'Cancel',
      uploadClass: 'btn btn-success fileinput-upload-button',
      uploadIcon: "<i class=\"glyphicon glyphicon-cloud-upload\"></i> ",
      uploadLabel: 'Import',
      indicatorNew: '<i class="glyphicon glyphicon-hand-down text-warning"></i>',
      indicatorSuccess: '<i class="glyphicon glyphicon-ok-sign file-icon-large text-success"></i>',
      indicatorError: '<i class="glyphicon glyphicon-exclamation-sign text-danger"></i>',
      indicatorLoading: '<i class="glyphicon glyphicon-hand-up text-muted"></i>',
      indicatorNewTitle: 'Not uploaded yet',
      indicatorSuccessTitle: 'Uploaded',
      indicatorErrorTitle: 'Upload Error',
      indicatorLoadingTitle: 'Uploading ...',
      allowedFileExtensions: ['csv'],
      msgValidationError: '<span class="text-danger">\n  <i class="glyphicon glyphicon-exclamation-sign"></i> 僅支持特定格式的CSV文件!\n</span>'
    }).on('filebatchselected', function(event, files) {
        $('#kv-success-1').hide();
        $('#kv-error-1').hide();
        var filesCount = $('#js-csv-upload').fileinput('getFilesCount');
        console.log(filesCount + " files selected");
    }).on('filebatchpreupload', function(event, data, id, index) {
        $('#kv-success-1').html('<h4>資料上傳狀態</h4><div id="file-info"></div><ul></ul>').hide();
        $('#kv-error-1').html('<h4>被略過的文件</h4><ul></ul>').hide();
    }).on('fileuploaded', function(event, data, id, index) {
        importedFiles += 1;
        console.log(importedFiles + " files imported");
        var fname = data.files[index].name,
            out = '<li>' + '文件' + (index + 1) + ' - ' + fname + ' 匯入成功' + '</li>';
        $('#kv-success-1 ul').append(out);
        $('#kv-success-1').fadeIn('slow');
    }).on('fileuploaderror', function(event, data, msg) {
        notImportedFiles += 1;
        var form = data.form, files = data.files, extra = data.extra,
            response = data.response, reader = data.reader;
        console.log(notImportedFiles + ' File upload error');
    }).on('filebatchuploadcomplete', function(event, files, extra) {
        console.log('File batch upload complete');

        var out = '<p class="text-primary">' + importedFiles + ' 個文件已成功匯入！' + ' ' + notImportedFiles + ' 個文件已被略過！' + '</p>';
        $('#kv-success-1 #file-info').append(out);
        // Reset counter
        importedFiles = 0
        notImportedFiles = 0
    }).on('filebrowse', function(event) {
        console.log("File browse triggered.");
    }).on('filepreajax', function(event, previewId, index) {
        console.log('File pre ajax triggered');
    }).on('filepreupload', function(event, data, previewId, index) {
        var form = data.form, files = data.files, extra = data.extra,
            response = data.response, reader = data.reader;
        console.log('File pre upload triggered');
    }).on('fileclear', function(event) {
        $('#kv-success-1').hide();
        $('#kv-error-1').hide();
        console.log("file cleared");
    });
  });

app/views/shared/_mi_import_form.html.haml
.form-group
  /= label_tag :file, "Choose CSV file to import", class: "control-label file_upload"
  = form_tag(mi_reports_path, method: 'post', remote: true, multipart: true) do
    %p
      %input#js-csv-upload-mi.file-loading{:accept => "text/csv", :multiple => "multiple", :name => "file[]", :type => "file", :webkitdirectory => ""}
      #kv-success-2.alert.alert-success.fade.in{:style => "margin-top:10px; display:none"}
      #kv-error-2{:style => "margin-top:10px; display:none"}
      /= file_field_tag :file, class: 'js-csv-upload', accept: 'text/csv'

:javascript
  jQuery(function() {
    var importedFiles = 0
    var notImportedFiles = 0
    $('#js-csv-upload-mi').fileinput({
      uploadUrl: "/mi_reports",
      uploadAsync: true,
      showPreview: false,
      showUpload: true,
      elErrorContainer: '#kv-error-2',
      browseOnZoneClick: true,
      browseClass: 'btn btn-info fileinput-browse-button',
      browseLabel: "選取文件",
      browseIcon: "<i class=\"glyphicon glyphicon-folder-open\"></i> ",
      removeClass: 'btn btn-danger',
      removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
      removeLabel: '取消',
      uploadClass: 'btn btn-success fileinput-upload-button',
      uploadIcon: "<i class=\"glyphicon glyphicon-cloud-upload\"></i> ",
      uploadLabel: '匯入',
      indicatorNew: '<i class="glyphicon glyphicon-hand-down text-warning"></i>',
      indicatorSuccess: '<i class="glyphicon glyphicon-ok-sign file-icon-large text-success"></i>',
      indicatorError: '<i class="glyphicon glyphicon-exclamation-sign text-danger"></i>',
      indicatorLoading: '<i class="glyphicon glyphicon-hand-up text-muted"></i>',
      indicatorNewTitle: '尚未匯入',
      indicatorSuccessTitle: '已經匯入',
      indicatorErrorTitle: '資料匯入時發生錯誤',
      indicatorLoadingTitle: '正在匯入資料...',
      allowedFileExtensions: ['csv'],
      msgValidationError: '<span class="text-danger">\n  <i class="glyphicon glyphicon-exclamation-sign"></i> 僅支持特定格式的CSV文件!\n</span>'
    }).on('filebatchselected', function(event, files) {
        $('#kv-success-2').hide();
        $('#kv-error-2').hide();
        var filesCount = $('#js-csv-upload').fileinput('getFilesCount');
        console.log(filesCount + " files selected");
    }).on('filebatchpreupload', function(event, data, id, index) {
        $('#kv-success-2').html('<h4>資料上傳狀態</h4><div id="file-info"></div><ul></ul>').hide();
        $('#kv-error-2').html('<h4>被略過的文件</h4><ul></ul>').hide();
    }).on('fileuploaded', function(event, data, id, index) {
        importedFiles += 1;
        console.log(importedFiles + " files imported");
        var fname = data.files[index].name,
            out = '<li>' + '文件' + (index + 1) + ' - ' + fname + ' 匯入成功' + '</li>';
        $('#kv-success-2 ul').append(out);
        $('#kv-success-2').fadeIn('slow');
    }).on('fileuploaderror', function(event, data, msg) {
        notImportedFiles += 1;
        var form = data.form, files = data.files, extra = data.extra,
            response = data.response, reader = data.reader;
        console.log(notImportedFiles + ' File upload error');
    }).on('filebatchuploadcomplete', function(event, files, extra) {
        console.log('File batch upload complete');

        var out = '<p class="text-primary">' + importedFiles + ' 個文件已成功匯入！' + ' ' + notImportedFiles + ' 個文件已被略過！' + '</p>';
        $('#kv-success-2 #file-info').append(out);
        // Reset counter
        importedFiles = 0
        notImportedFiles = 0
    }).on('filebrowse', function(event) {
        console.log("File browse triggered.");
    }).on('filepreajax', function(event, previewId, index) {
        console.log('File pre ajax triggered');
    }).on('filepreupload', function(event, data, previewId, index) {
        var form = data.form, files = data.files, extra = data.extra,
            response = data.response, reader = data.reader;
        console.log('File pre upload triggered');
    }).on('fileclear', function(event) {
        $('#kv-success-2').hide();
        $('#kv-error-2').hide();
        console.log("file cleared");
    });
  });

app/views/shared/_no_data.html.haml
.alert.alert-danger{ :role => "alert" }
  %span.glyphicon.glyphicon-exclamation-sign{"aria-hidden" => "true"}
  %a.close{ :href => "#", "data-dismiss" => "alert" } &times;
  從您選擇的日期，沒有找到任何資料！請用其他日期找找。

:javascript
  jQuery(function() {
    var flashCallback;
    flashCallback = function() {
      return $(".alert").fadeOut();
    };
    $(".alert").bind('click', (function(_this) {
      return function(ev) {
        return $(".alert").fadeOut();
      };
    })(this));
    return setTimeout(flashCallback, 3000);
  });

app/views/shared/_page_info.html.haml
- if @reports.count > 0
  - if params[:commit].present? && params[:commit] == "Search"
    共 #{@reports.total_count / @distinct_date.count} 筆資料
  - else
    在 #{@reports.current_page} / #{@reports.total_pages} 頁中，
    顯示共 #{@reports.total_count} 筆資料中的，
    第 #{@reports.offset_value + 1} 到 #{@reports.offset_value + @reports.length} 筆資料
- else
  沒有資料

app/views/shared/_page_info_scroll.html.haml
- if @reports.count > 0
  共 #{@reports.total_count} 筆資料中的 #{@reports.offset_value + @reports.length} 筆
- else
  沒有資料

app/views/shared/_search_box_range.html.haml
.entry-meta.row
  %aside.meta-details
    %h4 按連續日期比較各個分類指數
    #date-range
      = render :partial => "shared/date_range"
    #search.searchBox
      = form_tag search_my_post_reports_path(@post, build: params[:build]), method: :get, remote: true, id: "search-reports", class: 'row' do
        / .col-sm-12.col-md-3.inner-addon.left-addon
        /   %i.glyphicon.glyphicon-tags
        /   - if controller.controller_name == 'stations'
        /     / For Station page
        /     = autocomplete_field_tag :station, '', autocomplete_station_name_product_my_post_reports_path(@product, @post), class: 'form-control input-lg uneditable-input', value: "#{@station.name}", readonly: true
        /     = hidden_field_tag :from_station, "#{@station.id}"
        /   - else
        /     / For Post page
        /     = autocomplete_field_tag :station, '', autocomplete_station_name_my_post_reports_path(@post), class: 'form-control input-lg', placeholder: '分類指數名稱 (可不填)'

        .col-xs-12.col-sm-6.col-md-6.inner-addon.left-addon
          %i.glyphicon.glyphicon-calendar
          = text_field_tag :date_range, params[:date_range], id: 'search-daterange', class: 'daterange form-control input-lg', autocomplete: 'off', placeholder: '選擇日期區間'

        .col-xs-12.col-sm-6.col-md-6
          = hidden_field_tag :commit, "Search"
          = hidden_field_tag :search_type, "Range"
          %button#search-range-button.btn.btn-danger.btn-lg.btn-block.tclick.ladda-button{:type => "submit", "data-style" => "expand-right", :disabled => true}
            %span.glyphicon.glyphicon-search
            連續日期比較

:javascript
  $(function() {
    Ladda.bind( '.searchBox button[type=submit]' );
    $('button[type=submit]').click(function(e){
      $(document).ajaxStart(function(){
        $("#date-selector").fadeTo("fast", 0.3);
        $(".record_lists").fadeTo("fast", 0.3);
        $(".chart_section").fadeTo("fast", 0.3);
      });
      $(document).ajaxStop(function(){
        Ladda.stopAll();
        $("#date-selector").fadeTo("fast", 1.0);
        $(".record_lists").fadeTo("fast", 1.0);
        $(".chart_section").fadeTo("fast", 1.0);
      });
    });

    var start = moment().subtract(6, 'days');
    var end = moment();

    function cb2(start, end) {
        $('input[class="daterange"]').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }

    $('input[id="search-daterange"]').daterangepicker({
        startDate: start,
        endDate: end,
        autoApply: true,
        opens: "center",
        ranges: {
           '今天': [moment(), moment()],
           '過去 10 天': [moment().subtract(6, 'days'), moment()],
           '過去 15 天': [moment().subtract(14, 'days'), moment()],
           '過去 30 天': [moment().subtract(29, 'days'), moment()],
           '過去 60 天': [moment().subtract(59, 'days'), moment()]
        },
        maxDate: end,
        maxSpan: {
          days: 7
        },
        locale: {
          format: "YYYY-MM-DD",
          separator: " - "
        }
    }, cb2);

    cb2(start, end);

    $('input[id="search-daterange"]').on('apply.daterangepicker', function(ev, picker) {
      $('button#search-range-button').removeAttr('disabled');
      cb2(start, end);
    });

  });

app/views/shared/_search_box_stock.html.haml
.entry-meta.row
  %aside.meta-details
    %h4 按日期查詢分類指數的證券資料
    #date-range
      = render :partial => "shared/date_range"
    #search.searchBox
      = form_tag search_my_post_reports_path(@post, build: params[:build]), method: :get, remote: true, id: "search-reports", class: 'row' do
        .col-sm-12.col-md-3.inner-addon.left-addon
          = select("station", "id", Station.all.collect { |s| [ s.name, s.id ] }, {prompt: '選擇分類指數'}, {class: "selectpicker form-control", id: "station-picker", "data-live-search"=>"true", "data-style"=>"btn-lg btn-primary"})
          / %i.glyphicon.glyphicon-tags
          / - if controller.controller_name == 'stations'
          /   = autocomplete_field_tag :station, '', autocomplete_station_name_my_post_reports_path(@post), class: 'form-control input-lg uneditable-input', value: "#{@station.name}", readonly: true
          /   = hidden_field_tag :from_station, "#{@station.id}"
          / - else
          /   = autocomplete_field_tag :station, '', autocomplete_station_name_my_post_reports_path(@post), class: 'form-control input-lg', placeholder: '分類指數'

        .col-xs-12.col-sm-3.col-md-3.inner-addon.left-addon
          %i.glyphicon.glyphicon-calendar
          = text_field_tag :date, params[:date], id: 'search-date-fix', class: 'date-input-box date-fix form-control input-lg', autocomplete: 'off', placeholder: '選擇日期', disabled: true
        / .col-xs-6.col-sm-3.col-md-3.inner-addon.left-addon
        /   %i.glyphicon.glyphicon-calendar
        /   = text_field_tag :date2, params[:date2], id: 'search-date-fix', class: 'date-fix form-control input-lg', autocomplete: 'off', placeholder: '選擇日期2'
        / .col-xs-6.col-sm-3.col-md-3.inner-addon.left-addon
        /   %i.glyphicon.glyphicon-calendar
        /   = text_field_tag :date3, params[:date3], id: 'search-date-fix', class: 'date-fix form-control input-lg', autocomplete: 'off', placeholder: '選擇日期3'

        .col-xs-12.col-sm-6.col-md-6
          = hidden_field_tag :commit, "Search"
          = hidden_field_tag :search_type, "Stock"
          %button#search-button.btn.btn-success.btn-lg.btn-block.tclick.ladda-button{:type => "submit", "data-style" => "expand-right", :disabled => true}
            %span.glyphicon.glyphicon-search
            查詢證券資料

:javascript
  $(document).ready(function(){
    $('select').selectpicker();
  });

  $(function() {
    $('select').on('change', function () {
      var isSelected = !this.options[this.selectedIndex].defaultSelected;
      if (isSelected) {
          $('.date-input-box').removeAttr('disabled');
      }
    });
    Ladda.bind( '.searchBox button[type=submit]' );
    $('button[type=submit]').click(function(e){
      $(document).ajaxStart(function(){
        $("#date-selector").fadeTo("fast", 0.3);
        $(".record_lists").fadeTo("fast", 0.3);
        $(".chart_section").fadeTo("fast", 0.3);
      });
      $(document).ajaxStop(function(){
        Ladda.stopAll();
        $("#date-selector").fadeTo("fast", 1.0);
        $(".record_lists").fadeTo("fast", 1.0);
        $(".chart_section").fadeTo("fast", 1.0);
      });
    });

    var start = moment().subtract(0, 'days');
    var end = moment();

    function cb(start, end) {
        $('input[class="fix-date"]').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    }

    $('input[id="search-date-fix"]').daterangepicker({
        autoUpdateInput: false,
        singleDatePicker: true,
        locale: {
          format: "YYYY-MM-DD",
          separator: " - "
        }
    });

    $('input[id="search-date-fix"]').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('YYYY-MM-DD'));

      $('button#search-button').removeAttr('disabled');
    });

    $('input[id="search-date-fix"]').change(function() {
      var empty = true;
      $('form > input').each(function() {
        if ($(this).val() !== '') {
          empty = false;
        }
      });

      if (empty) {
          $('button#search-button').attr('disabled', 'disabled');
      } else {
          $('button#search-button').removeAttr('disabled');
      }
    });

    cb(start, end);

  });

app/views/shared/_tab_search.html.haml
%ul.nav.nav-tabs{:style => "margin-bottom: 15px;"}
  / Show tab for Global Search results
  - if params[:commit] == 'GlobalSearch'
    %li.active{:role => "presentation"}
      %a{:href => "#", "data-remote" => "true"}
        %span.glyphicon.glyphicon-search
        Search Result
        - if current_page?(:controller => controller.controller_name, :action => controller.action_name, :page => params[:page])
          %span.badge= @reports_for_cart.count.to_i

:javascript
  $(document).ready(function() {
    // hide spinner
    $(".sk-three-bounce").hide();
  });