config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"
  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, only: [:index, :show] do
        resources :reports, only: [:index, :show, :destroy]
      end
      resources :my_posts, except:  [:edit, :new] do
        resources :reports, only: [:index, :show]
        resources :stations, only: [:index] do
          resources :reports, only: [:index]
        end
      end
      resources :users, only: [:show]
    end
  end

  resources :posts

  resources :mi_reports, only: [:create]

  resources :reports, only: [:create] do
    get :autocomplete_station, :on => :collection
    get :autocomplete_config, :on => :collection
    collection do
      get :search
      post :import
    end
  end

  resources :my_posts, only: [:index, :show, :destroy] do
    resources :reports, only: [:show] do
      get :autocomplete_station_name, :on => :collection
      get :autocomplete_report_config, :on => :collection
      collection do
        get :search
      end
      resources :configs, only: [:index]
    end
    resources :stations, only: [:show]
    resources :yield_files, only: [:index, :show, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end
  end

  match "/update_builds_selector" => "products#update_builds_selector"
  match "/update_builds_menu" => "products#update_builds_menu"
  match "/delete_account" => "accounts#checkpass"

  match "/search_report" => "reports#search"

  root :to => 'main#index'

  get '*anything' => 'errors#routing_error'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :user_id

  belongs_to :user

  has_many :posts, dependent: :destroy

  validates :title, presence: true, length: { :minimum => 3, :maximum => 255 }

  paginates_per 100
end

app/models/user.rb
#require 'Houston'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessible :provider, :uid

  attr_accessor :facebook_user

  has_many :devices, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :products, :dependent => :destroy
  has_many :access_grants, :dependent => :destroy, :class_name => "Doorkeeper::AccessGrant", :foreign_key => "resource_owner_id"
  has_many :access_tokens, :dependent => :destroy, :class_name => "Doorkeeper::AccessToken", :foreign_key => "resource_owner_id"

  # validates_presence_of   :email, :if => :email_required?
  # validates_uniqueness_of :email, :allow_blank => true, :if => :email_changed?
  # validates_format_of     :email, :with  => email_regexp, :allow_blank => true, :if => :email_changed?

  # validates_presence_of     :password, :if => :password_required?
  # validates_confirmation_of :password, :if => :password_required?
  # validates_length_of       :password, :within => password_length, :allow_blank => true

  def self.send_notify_ios(text, data = nil)
    certificate = File.read(ENV['APPLE_CERTIFICATE'])
    passphrase = ENV['APN_CERTIFICATE_PASSPHRASE']
    connection = Houston::Connection.new(Houston::APPLE_DEVELOPMENT_GATEWAY_URI, certificate, passphrase)
    connection.open

    #apn = Houston::Client.development
    #apn.certificate = File.read(ENV['APPLE_CERTIFICATE']) # certificate from prerequisites
    Device.where(platform: 'ios').each do |device|
      notification = Houston::Notification.new(device: device.uuid)
      notification.alert = text
      notification.badge = 1
      notification.content_available = true
      notification.mutable_content = true
      #notification.sound = 'sound.aiff'
      #notification.category = 'INVITE_CATEGORY'
      #notification.custom_data = { foo: 'bar', alice: 'bob' }
      notification.custom_data = data unless data.nil?
      connection.write(notification.message)
      connection.close
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.create(
        # name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
    end

    if user.valid?
      user.facebook_token = auth.credentials.token
      user.facebook_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end

    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def facebook
    if !@facebook && facebook_token && facebook_expires_at > Time.now
      @facebook = Koala::Facebook::API.new(facebook_token)
    end
    @facebook
  end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  before_filter :authenticate_user!

  def index
  	@products = Product.find(:all, order: 'title')
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(params[:product])
    @product.user = current_user
    
    respond_to do |format|
      if @product.save
      	format.js
        format.html { redirect_to products_path, notice: "#{@product.title} was successfully created." }
        format.json { head :no_content }
      else
      	format.js
        format.html { render action: 'new' }
        format.json { head :no_content }
      end
    end
  end

  def destroy
  	@product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.js { head :ok }
      format.html { redirect_to products_path, notice: "#{@product.title} was removed." }
      format.json { head :no_content }
    end
  end

  def update_builds_selector
    @builds = Post.where(product_id: params[:product_id]).all
    #render partial: '/shared/builds_selector', object: @builds
  end

  def update_builds_menu
    @product = Product.find_by_title(params[:product_name].strip!)
    @builds = Post.where(product_id: @product).all
  end
end

app/views/products/_form.html.haml
.row
  .container
    = form_for(@product, :url => products_path, :html => { :class => "well", :role => "form" }) do |f|
      - if @product.errors.any?
        #error_explanation
          %h2
            = pluralize(@product.errors.count, "error")
            prohibited this post from being saved:
          %ul
            - @product.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.label :title
        = f.text_field :title, :style => "width: 99%;", class: "form-control", placeholder: "Product name"
      
      %button{ :type => "submit", :class => "btn btn-primary" } Create Product

app/views/products/index.html.haml
- navigation_add 'Products', products_path

%h2.page-header
  Products
  %small
    = @products.count
    product(s)
%p.lead Click one of the product to check all builds for it

.row
  .product-lists
    .col-md-8.col-md-offset-2
      .panel.panel-custom.panel-default
        .panel-body
          .pull-right
            .table-filter
              .btn-group
                %button.btn.btn-primary{"data-toggle" => "modal", :href => "#importCSV"}
                  %span.glyphicon.glyphicon-cloud-upload{"aria-hidden" => "true"}
                  Import File
          .table-container
            %table.table.table-hover.table-filter
              %tbody
                - @products.each do |product|
                  %tr{id: "product_row_#{product.id}"}
                    %td{:style => "vertical-align: middle;"}
                      .ckbox
                        = check_box_tag "product_ids[]", product.id, false, :id => "product_ids_#{product.id}"
                        %label{:for => "product_ids_#{product.id}"}
                    %td{:style => "vertical-align: middle;"}
                      %a.star{:href => "javascript:;", "data-toggle" => "tooltip", title: "No function yet"}
                        %i.glyphicon.glyphicon-star
                    %td
                      .media
                        .media-body
                          %span.media-meta.pull-right= product.created_at.to_date.to_formatted_s(:long)
                          %h4.title
                            = link_to product.title, product_my_posts_path(product)
                            %span#delete-product.pull-right.dont_show
                              /= link_to '(Delete)', product_path(product), data: { confirm: "All imported yield files and records from #{product.title} will be permanently deleted. Are you sure?" }, method: :delete, :class => "text-danger"
                              = link_to '(Delete)', '#', :class => "text-danger", id: "delete-a-product", "data-product-name" => "#{product.title}", "data-product-id" => "#{product.id}"
                          %p.summary
                            - if product.posts.count > 0
                              = product.posts.count.to_i
                              build(s) included in the product
                            - else
                              No build included in the product

= render :partial => "shared/csv_importer"

:javascript
  $(document).ready(function () {
    $('[data-toggle="tooltip"]').tooltip();

    $('.star').on('click', function () {
      $(this).toggleClass('star-checked');
    });

    $('.ckbox label').on('click', function () {
      $(this).parents('tr').toggleClass('selected');
      var checked = $(this).find("input:checkbox").is(":checked");
      if(checked){
        $(this).parents('tr').find('#delete-product').removeClass('dont_show');
      }
      else {
        $(this).parents('tr').find('#delete-product').toggleClass('dont_show');
      }
    });
  });

  $("a#delete-a-product").click(function() {
    var productName = $(this).attr("data-product-name");
    var productId = $(this).attr("data-product-id");
    deleteProduct(productName, productId);
  });

  function deleteProduct(productName, productId) {
    swal({
      title: "Are you sure?", 
      text: "You want to delete " + productName, 
      type: "warning",
      showCancelButton: true,
      closeOnConfirm: false,
      confirmButtonClass: "btn-warning",
      confirmButtonText: "Delete it!",
      closeOnConfirm: false,
      showLoaderOnConfirm: true
    }, function() {
      $.ajax({
        url: "/products/" + productId,
        type: "DELETE",
        dataType: 'script'
      })
      .done(function(data) {
        swal("Successfully Deleted!", productName + " was successfully deleted!", "success");
        $("#product_row_" + productId).fadeOut();

        $('button.confirm').click(function() {
          setTimeout(function(){
            $(location).attr('href', "/products")
          }, 200);
        });
      })
      .error(function(data) {
        swal("Something went wrong", "We couldn't connect to the server!", "error");
      });
    });
  }

app/views/products/index.js.erb
$('#product-items').html("<%= j(render :partial => 'product_items') %>");
$('#paginator').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/products/new.html.haml
- navigation_add 'New Product', new_product_path

%h2.page-header
  New Product
  %small Create a new product
%p.lead Create a product name (ex. JH3/JH4) to organize and manage different build

= render 'form'

app/views/products/update_builds_menu.js.erb
$('#dropdown-build-selector').html("<%= j(render :partial => 'shared/dropdown_build_selector') %>");

app/views/products/update_builds_selector.js.erb
$('#build-to-select').html("<%= j(render :partial => 'shared/builds_selector') %>");
$('#station-to-select').html("<%= j(render :partial => 'shared/stations_selector') %>");
$('#config-to-select').html("<%= j(render :partial => 'shared/configs_selector') %>");
$('#search-button').html("<%= j(render :partial => 'shared/search_button') %>");