config/routes.rb
Bestmix::Application.routes.draw do
  get "my_posts/index"
  get "my_posts/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount Doorkeeper::Engine => '/oauth'

  get 'oauth/token' => 'doorkeeper/tokens#create'

  devise_for :users

  namespace :api do
    api_version(:module => "V1", :path => "/v1") do
      resources :posts, only: [:index, :show] do
        resources :reports, only: [:index, :show, :destroy]
      end
      resources :my_posts, except:  [:edit, :new] do
        resources :reports, only: [:index, :show]
        resources :stations, only: [:index] do
          resources :reports, only: [:index]
        end
      end
      resources :users, only: [:show]
    end
  end

  resources :posts

  resources :mi_reports, only: [:create]

  resources :reports, only: [:create] do
    get :autocomplete_station, :on => :collection
    get :autocomplete_config, :on => :collection
    collection do
      get :search
      post :import
    end
  end

  resources :my_posts, only: [:index, :show, :destroy] do
    resources :reports, only: [:show] do
      get :autocomplete_station_name, :on => :collection
      get :autocomplete_report_config, :on => :collection
      collection do
        get :search
      end
      resources :configs, only: [:index]
    end
    resources :stations, only: [:show]
    resources :yield_files, only: [:index, :show, :destroy] do
      collection do
        delete :destroy_multiple
      end
    end
  end

  match "/update_builds_selector" => "products#update_builds_selector"
  match "/update_builds_menu" => "products#update_builds_menu"
  match "/delete_account" => "accounts#checkpass"

  match "/search_report" => "reports#search"

  root :to => 'main#index'

  get '*anything' => 'errors#routing_error'

end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::ApiController
  doorkeeper_for :all

  def index
  	page = (params[:page] || 1).to_i
	per_page = 25
    expires_in 5.seconds
    
  	@post = current_user.posts.find_by_id(params[:my_post_id])
  	@station = @post.stations.find_by_id(params[:station_id]) if params[:station_id]
    if @post.nil?
      render_error(
        :resource_not_found,
        "Not Found",
        "Requested yield report post does not exist or you don't have permission to see it."
      )
      return
    end
	
    if page > 1 || stale?(last_modified: @post.reports.maximum(:updated_at))
      # Ordered by parameters
      if !params[:sort].blank?
      	if (Report.column_names.include? params[:sort]) && (Report.sort_names.include? params[:sort])
      	  @reports = params[:station_id] ? @station.reports.order("#{params[:sort]} ASC").page(page).per(per_page) : @post.reports.order("#{params[:sort]} ASC").page(page).per(per_page)
      	else
      	  render_error(
        	:resource_not_found,
        	"Parameter Error",
        	"'#{params[:sort]}' is not a valid parameter."
      	  )
      	  return
      	end
      else
      	# Ordered by published_at as default
      	@reports = params[:station_id] ? @station.reports.order("published_at ASC").page(page).per(per_page) : @post.reports.order("published_at ASC").page(page).per(per_page)
  	  end
    end
  end

  def show
  	@post = current_user.posts.find_by_id(params[:my_post_id])
    @report = @post.reports.find_by_id(params[:id])
    if @report.nil?
      render_error(
        :resource_not_found,
        "Not Found",
        "Requested yield data does not exist or you don't have permission to see it."
      )
      return
    end
    expires_in 5.seconds
    fresh_when @report, public: true
  end

  def destroy
    @post = current_user.posts.find_by_id(params[:my_post_id])
    @report = @post.reports.find_by_id(params[:id])
    if @report.nil?
      render_error(
        :resource_not_found,
        "Not Found",
        "Requested yield data does not exist or you don't have permission to see it."
      )
      return
    end
    @report.destroy
    render :action => :show
  end
end

app/helpers/api/v1/reports_helper.rb
module Api::V1::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
  def best_percentage_chart_data(reports)
    start_time = reports.last.published_at
    end_time = reports.first.published_at
    post_id = reports.first.post_id
    if controller.controller_name == "reports"
      # For search build page
      datetime = reports.select("distinct(published_at)")
    else
      # For general build page
      datetime = Report.where("post_id = ? AND published_at BETWEEN ? AND ?", post_id, start_time, end_time).select("distinct(published_at)")
    end
    datetime.map do |date|
    {
      published_at: date.published_at.to_datetime.to_formatted_s(:long),
      # Top1 shares percentage & closing percentage & station name
      best1_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).first.try(:best_shares_percentage),
      best1_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).first.try(:best_closing_percentage),
      best1_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).first.try(:station_name),
      best1_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).first.try(:station_name),
      
      # Top2 shares percentage & closing percentage & station name
      best2_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(1).first.try(:best_shares_percentage),
      best2_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(1).first.try(:best_closing_percentage),
      best2_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(1).first.try(:station_name),
      best2_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(1).first.try(:station_name),
      
      # Top3 shares percentage & closing percentage & station name
      best3_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(2).first.try(:best_shares_percentage),
      best3_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(2).first.try(:best_closing_percentage),
      best3_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(2).first.try(:station_name),
      best3_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(2).first.try(:station_name),
      
      # Top4 shares percentage & closing percentage & station name
      best4_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(3).first.try(:best_shares_percentage),
      best4_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(3).first.try(:best_closing_percentage),
      best4_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(3).first.try(:station_name),
      best4_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(3).first.try(:station_name),
      
      # Top5 shares percentage & closing percentage & station name
      best5_shares_percentage: Report.group_shares_percentage_by_date(date.published_at).offset(4).first.try(:best_shares_percentage),
      best5_closing_percentage: Report.group_closing_percentage_by_date(date.published_at).offset(4).first.try(:best_closing_percentage),
      best5_shares_percentage_index: Report.group_shares_percentage_by_date(date.published_at).offset(4).first.try(:station_name),
      best5_closing_percentage_index: Report.group_closing_percentage_by_date(date.published_at).offset(4).first.try(:station_name),
    }
    end
  end

  def config_accu_yield_bar_chart_data(reports)
    station = reports.first.station_name
    config = reports.first.config
    datetime_start = reports.minimum('published_at')
    datetime_end = reports.maximum('published_at')

    if params[:data_period].present? && params[:data_period] == "hourly"
      # If parameter present, show each hour's report
      overflow_accu_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate > ?", config, station, datetime_start, datetime_end, 100.00).count
      great_accu_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, station, datetime_start, datetime_end, 99.51, 100.00).count
      bad_accu_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, station, datetime_start, datetime_end, 90.00, 99.50).count
      worse_accu_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate >= ? AND yield_rate <= ?", config, station, datetime_start, datetime_end, 0.00, 89.99).count
      no_input_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate IS NULL", config, station, datetime_start, datetime_end).count
    else
      # By default, only show latest hour's report for each day
      overflow_accu_yield = reports.where("yield_rate > ?", 100.00).count
      great_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 99.51, 100.00).count
      bad_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 90.00, 99.50).count
      worse_accu_yield = reports.where("yield_rate >= ? AND yield_rate <= ?", 0.00, 89.99).count
      no_input_yield = reports.where("yield_rate IS NULL").count
    end

    overflow_accu_yield_rate = ((overflow_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    great_accu_yield_rate = ((great_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    bad_accu_yield_rate = ((bad_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    worse_accu_yield_rate = ((worse_accu_yield.to_f / reports.count.to_f) * 100).round(2)
    no_input_yield_rate = ((no_input_yield.to_f / reports.count.to_f) * 100).round(2)

    range_array = [overflow_accu_yield, great_accu_yield, bad_accu_yield, worse_accu_yield, no_input_yield]
    title = ['Overflow Accu Yield', 'Verified Accu Yield', 'Bad Accu Yield', 'Worse Accu Yield', 'No Input']
    percent = [overflow_accu_yield_rate, great_accu_yield_rate, bad_accu_yield_rate, worse_accu_yield_rate, no_input_yield_rate]

    range_array.map.with_index do |range, index| {  
      value: range,
      label: title[index],
      percent: percent[index]
    }
    end
  end

  def config_daily_yield_bar_chart_data(reports)
    station = reports.first.station_name
    config = reports.first.config
    datetime_start = reports.minimum('published_at')
    datetime_end = reports.maximum('published_at')

    if params[:data_period].present? && params[:data_period] == "hourly"
      # If parameter present, show each hour's report
      overflow_daily_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today > ?", config, station, datetime_start, datetime_end, 100.00).count
      great_daily_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, station, datetime_start, datetime_end, 99.51, 100.00).count
      bad_daily_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, station, datetime_start, datetime_end, 90.00, 99.50).count
      worse_daily_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today >= ? AND yield_rate_today <= ?", config, station, datetime_start, datetime_end, 0.00, 89.99).count
      no_input_yield = Report.where("config = ? AND station_name = ? AND published_at BETWEEN ? AND ? AND yield_rate_today IS NULL", config, station, datetime_start, datetime_end).count
    else
      # By default, only show latest hour's report for each day
      overflow_daily_yield = reports.where("yield_rate_today > ?", 100.00).count
      great_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 99.51, 100.00).count
      bad_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 90.00, 99.50).count
      worse_daily_yield = reports.where("yield_rate_today >= ? AND yield_rate_today <= ?", 0.00, 89.99).count
      no_input_yield = reports.where("yield_rate_today IS NULL").count
    end

    overflow_daily_yield_rate = ((overflow_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    great_daily_yield_rate = ((great_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    bad_daily_yield_rate = ((bad_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    worse_daily_yield_rate = ((worse_daily_yield.to_f / reports.count.to_f) * 100).round(2)
    no_input_yield_rate = ((no_input_yield.to_f / reports.count.to_f) * 100).round(2)

    range_array = [overflow_daily_yield, great_daily_yield, bad_daily_yield, worse_daily_yield, no_input_yield]
    title = ['Overflow Daily Yield', 'Verified Daily Yield', 'Bad Daily Yield', 'Worse Daily Yield', 'No Input']
    percent = [overflow_daily_yield_rate, great_daily_yield_rate, bad_daily_yield_rate, worse_daily_yield_rate, no_input_yield_rate]

    range_array.map.with_index do |range, index| {  
      value: range,
      label: title[index],
      percent: percent[index]
    }
    end
  end
end

app/views/reports/_chart_by_search.html.haml
- if params[:station].present? && params[:station] != ""
  = render :partial => "configs/best_percentage_cart"
- elsif params[:from_station].present? && params[:from_station] != ""
  = render :partial => "stations/station_yield_cart"
- elsif params[:from_report].present? && params[:from_report] != ""
  = render :partial => "configs/yield_ratio_chart"
- else
  = render :partial => "my_posts/worst_yield_cart"

app/views/reports/search.html.haml
- navigation_add 'Search Results', search_reports_path

%h2.page-header
  Searched for
  %small
    %strong
      - if params[:product_id].present?
        = link_to @product.title, my_posts_path
      - if params[:my_post_id].present?
        &gt;
        = link_to @post.title, my_post_path(@post)
      - if params[:station].present?
        &gt;
        = link_to params[:station], my_post_station_path(@post, @station)
      - if params[:config].present?
        &gt;
        #{params[:config]}
.form-group
  .row
    .col-md-12
      #yield-report
        = render :partial => "shared/yield_report"

app/views/reports/search.js.erb
<% unless params[:commit].present? && params[:commit] == "Search" && @distinct_date.count == 0 %>
	$('#date-range').html("<%= j(render :partial => 'shared/date_range') %>");
	$('#date-selector').html("<%= j(render :partial => 'shared/date_selector') %>");
	$('#tab-selector').html("<%= j(render :partial => 'shared/tab_selector') %>");
	//$('#yield-items').html("<%= j(render :partial => 'shared/yield_items') %>");

	// Date Range SLider
	$('#date-slider-box').html("<%= j(render :partial => 'shared/date_slider') %>");
	// Rendering Chart according to search input
	$('#worst-yield-cart').html("<%= j(render :partial => 'chart_by_search') %>");
	$('#station-yield-cart').html("<%= j(render :partial => 'chart_by_search') %>");
	$('#yield-ratio-chart-data').html("<%= j(render :partial => 'chart_by_search') %>");

	// Pagination
	$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
	$('#paginator-top').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
	$('#page-info').html("<%= j(render :partial => 'shared/page_info') %>");
	//$(".pagination").rPage();

	<% if !params[:page].present? %>
		$('#yield-items').html("<%= j(render :partial => 'shared/yield_items') %>");
	<% else %>
		$("<%=j render(:partial => 'shared/items', :object => @reports) %>").appendTo($(".infinite-table"));
	<% end %>

	// Update pagination link
	<% if @reports.last_page? %>
		$('.pagination').html("That's all, dude!");
	<% elsif params[:search_type] %>
		$('.pagination').html("");
	<% else %>
		//$('#paginator').html('<%= escape_javascript(paginate(@reports, :remote => true).to_s) %>');
		$('#paginator').html('<%= escape_javascript(link_to_next_page(@reports, '載入更多資料', params: params, :remote => true).to_s) %>');
	<% end %>

	$("#chart-graph").fadeTo("fast", 1.0);
<% else %>
	$('#no-data-found').html("<%= j(render :partial => 'shared/no_data') %>");

	$('#date-range').html("<%= j(render :partial => 'shared/date_range') %>");
	$('#date-selector').html("<%= j(render :partial => 'shared/date_selector') %>");
	$('#tab-selector').html("<%= j(render :partial => 'shared/tab_selector') %>");

	$('#yield-items').html("<%= j(render :partial => 'shared/yield_items') %>");

	$("#chart-graph").fadeTo("fast", 0.3);
<% end %>

app/views/reports/show.html.haml
- build_type = params[:build].nil? ? "" : " (" + params[:build].to_s.upcase + ")"

- navigation_add 'Products', products_path
- navigation_add @product.title + ' Builds', product_my_posts_path(@product)
- navigation_add @post.title + build_type, product_my_post_path(@product, @post, :build => params[:build])
- navigation_add @report.station_name, product_my_post_report_path(@product, @post, @report)

%h2.page-header
  = @report.station_name
  %small= @report.published_at.to_formatted_s(:long)

.row
  .container
    .panel.panel-default
      .panel-heading
        Detail Information
      .panel-body
        .table-responsive
          %table.table.table-bordered.table-striped{:style => "width: 100%;"}
            %thead
              %tr
                %th Item
                %th Value
            %tbody
              %tr
                %th Accu Yield
                %td= render_yield_rate(@report.yield_rate)
              %tr
                %th Daily Yield
                %td= render_yield_rate(@report.yield_rate_today)
              %tr
                %th FP Accu Yield
                %td= render_yield_rate(@report.fp_yield_rate)
              %tr
                %th FP Daily Yield
                %td= render_yield_rate(@report.fp_yield_rate_today)
              %tr
                %th Input Today
                %td= @report.input_today
              %tr
                %th Output Today
                %td= @report.output_today
              %tr
                %th Seqno
                %td= @report.seqno
              %tr
                %th Config
                -if @report.config == 'ALL'
                  %td= @report.config
                - else
                  %td
                    %span.badge.progress-bar-info
                      = @report.config
              %tr
                %th Input
                %td= @report.input
              %tr
                %th PFirstPass
                %td= @report.first_pass
              %tr
                %th PRetestPass
                %td= @report.retest_pass
              %tr
                %th Fail
                %td= @report.fail
              %tr
                %th RetestProcess
                %td= @report.retest_process
              %tr
                %th TestWF
                %td= @report.test_waive
              %tr
                %th DesignWF
                %td= @report.design_waive
              %tr
                %th COFWF
                %td= @report.cof_waive
              %tr
                %th RDArea
                %td= @report.rd_area
              %tr
                %th BPL
                %td= @report.bpl
              %tr
                %th NTF
                %td= @report.ntf
              %tr
                %th FailureWF
                %td= @report.failure_waive
              %tr
                %th RepairOK
                %td= @report.repaire_ok
              %tr
                %th INLRepair
                %td= @report.inl_repaire
              %tr
                %th DIP
                %td= @report.dip
              %tr
                %th Defect
                %td= @report.defect
              %tr
                %th Fail_Borrow
                %td= @report.fail_borrow
              %tr
                %th Pass_Borrow
                %td= @report.pass_borrow
              %tr
                %th Type
                %td= @report.yield_type
              %tr
                %th Source File
                %td= link_to @report.yield_file.file_name, product_my_post_yield_file_path(@product, @post, @report.yield_file)
                //%td= @report.yield_file.file_name